version: "3.4"

services:
  logindfehelp:
    image: logindfehelp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      settings: ./config/login.dfe.help.local.json
    ports:
      - 4439:4439
