name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops.pipelines
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - feature/*

variables:
- group: platform-global
- group: code-scan-tools
- name: applicationName
  value: hlp
# - name: environmentName
#   - ${{ if eq(parameters.gitVersioning, true) }}:
#     value: 

stages:
# Code scaning tools 
- template: ./scan-tools.yml
# Build the artifact for deployment
- stage: build
  jobs:
  - template: ./build.yml
    parameters:
      applicationName: $(applicationName)
      custRegAuth: $(custRegAuth)
      artifactName: "$(applicationName)-dev-$(Build.BuildId)-release"
      variableGroups:
        - platform-dev
        - platform-dev-secured
        - platform-standalone-azure-hosts

      # stageName: publishDevInstances
      # serviceConnection: "${{parameters.devServiceConnection}}"
      # resourceGroupSuffix: "${{parameters.resourceGroupSuffix}}"
      # environmentName: dev
      # environmentId: d01
      # deploymentDependencyName: deployDev
      # accessRestricted: "${{parameters.restrictToGateway}}"
      # gatewayFrontEndHostName: ""