name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops.pipelines
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - feature/*

variables:
- group: platform-global

stages:
- stage: build
  jobs:
  - template: build.yml