name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7180
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.dsi-config
      ref: main

trigger:
  branches:
    include:
    - feature/*
    - main
    - release/*

pr:
  branches:
    include:
    - main

parameters:
- name: InfrDeploy
  type: boolean
  displayName: 'Infrastrucure Deployment only'
  default: false

variables:
- group: dsi-global
- name: applicationFullName
  value: 'help'

stages:

# Code Scans & Build the artifact for deployment
- stage: scanBuildApp
  displayName: "Scan tools & Build"
  jobs:

  - template:  pipeline/scanTools.yml@devopsTemplates
    parameters:
      npmInstCmd: 'install --force --json --no-package-lock'
      AppDeploy: ${{ not(parameters.InfrDeploy) }}

  - ${{ if not(eq(parameters.InfrDeploy, 'true')) }}:
    - template: pipeline/build.yml@devopsTemplates
      parameters:
        applicationName: ${{variables.applicationFullName}}
        custRegAuth: $(custRegAuth)
        pm2ProcessFileName: process.json
        nodeVersionSpec: '18.17.0'
        npmInstCmd: 'install --force --json --no-package-lock'
        npmPruneFixCmd: 'install --production --json --force --no-package-lock'