name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config
      ref: master

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    #- feature/*

variables:
- group: platform-global
- group: code-scan-tools
- name: applicationShortName
  value: 'hlp'
- name: applicationFullName
  value: 'help'
# - name: environmentName
#   - ${{ if eq(parameters.gitVersioning, true) }}:
#     value: 

stages:
# Check What Folder/files changes to trigger the correspondent stages
- stage: FilesChanges
  displayName: "Files Changes"
  jobs:
  - job: filesCheckStatus

    steps:
    - task: PowerShell@2
      displayName: Files Check
      name: filesCheck
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          $Check= "true"
          $editedFiles = git diff HEAD HEAD~ --name-only
          $editedFiles | ForEach-Object {
              Write-Output $_
              Switch -Wildcard ($_ ) {
                  'DevOps/*' { Write-Host "##vso[task.setvariable variable=InfrDeploy;]1.5.4" }
                  'src/*' { Write-Host "##vso[task.setvariable variable=AppDeploy;]$Check"  }
                  'test/*' { Write-Host "##vso[task.setvariable variable=AppDeploy;]$Check" }
                  '*package*' { Write-Host "##vso[task.setvariable variable=AppDeploy;]$Check" }
                  # The rest of your path filters
              }

          }

          Write-Host "##vso[task.setvariable variable=EnvVariable;isOutput=true]$Check"
          Write-Host "##vso[task.setvariable variable=InfrDeploy;isOutput=true]$Check"

          Write-Output "##vso[task.setvariable variable=EnvVariable;isOutput=true]$Check"
          Write-Output "##vso[task.setvariable variable=InfrDeploy;isOutput=true]$Check"
    - task: PowerShell@2
      displayName: Read variables 0
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          Get-ChildItem -Path Env:\ | Format-List
          Write-Host "env:EnvVariable : $($env:ENVVARIABLE)"

          Write-Host "ENV:EnvVariable : $($ENV:ENVVARIABLE)"

          Write-Output "env:EnvVariable : $($env:ENVVARIABLE)"

          Write-Output "ENV:EnvVariable : $($ENV:ENVVARIABLE)"

          Write-Output "ENV:InfrDeploy : $($ENV:INFRDEPLOY)"
          Write-Output "ENV:AppDeploy : $($env:APPDEPLOY)"

# Code scaning tools 
#- template: ./scan-tools.yml

#Build the artifact for deployment
- stage: buildApp
  displayName: "Package application"
  condition: eq(variables['AppDeploy'], 'true')
  #dependsOn: scanTools
  jobs:
  - template: ./build.yml
    parameters:
      applicationName: ${{variables.applicationFullName}}
      custRegAuth: $(custRegAuth)
      artifactName: "${{variables.applicationShortName}}-dev-$(Build.BuildId)-release"
      environmentName: dev
      pm2ProcessFileName: process.json
      variableGroups:
        - platform-dev
        - platform-dev-secured
        - platform-standalone-custom-hosts

- stage: DeployApp
  dependsOn: buildApp
  displayName: "Deploy application"
  condition: and(eq(variables['AppDeploy'], 'true'),eq(variables['InfrDeploy'], 'False'))
  jobs:
  - template: ./deploy.yml
    parameters:
      serviceConnection: "$(devServiceConnection)"
      environmentName: dev
      environmentId: d01
      subscriptionId: $(devSubscriptionId)
      applicationName: ${{variables.applicationShortName}}
      releaseArtifactName: ${{variables.applicationShortName}}-dev-$(Build.BuildId)-release

- stage: DeployInfr
  displayName: "Deploy Infrastructure"
  condition: eq(stageDependencies.FilesChanges.filesCheckStatus.outputs['filesCheck.InfrDeploy'], 'true')
  variables: 
    InfrDeploy: $[stageDependencies.FilesChanges.filesCheckStatus.outputs['filesCheck.InfrDeploy']]
  jobs:
  - template: ./infrastructure.yml
    parameters:
      serviceConnection: "$(devServiceConnection)"
      environmentName: dev
      environmentId: d01
      subscriptionId: $(devSubscriptionId)
      applicationShortName: ${{variables.applicationShortName}}
      applicationFullName: ${{variables.applicationFullName}}
      releaseArtifactName: ${{variables.applicationShortName}}-dev-$(Build.BuildId)-release
      certificateName: non-prod-gateway
      variableGroups:
        - platform-dev
        - platform-dev-secured
        - platform-standalone-custom-hosts


#       # stageName: publishDevInstances
#       # 
#       # resourceGroupSuffix: "${{parameters.resourceGroupSuffix}}"
#       # environmentName: dev
#       # environmentId: d01
#       # deploymentDependencyName: deployDev
#       # accessRestricted: "${{parameters.restrictToGateway}}"
#       # gatewayFrontEndHostName: ""