name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-5540
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config
      ref: master

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    #- feature/*

parameters:
- name: AppDeploy
  type: boolean
  default: true
- name: InfrDeploy
  type: boolean
  default: true

variables:
- group: dsi-dev-kv
- group: dsi-global
- name: applicationShortName
  value: 'hlp'
- name: applicationFullName
  value: 'help'
- name: numberOfWorkers
  value: 1
- name: environmentName
  value: dev
# - name: environmentName
#   - ${{ if eq(parameters.gitVersioning, true) }}:
#     value: 

stages:

# Code Scans & Build the artifact for deployment
- stage: buildApp
  displayName: "Scan tools & Build"
  condition: and(succeeded(), ${{ parameters.AppDeploy }})
  jobs:
    # Code scaning tools
  - template:  pipeline/checkov.yml@devopsTemplates

  - template:  pipeline/eslint.yml@devopsTemplates

  - template:  pipeline/dependencyCheck.yml@devopsTemplates
    parameters:
      npmInstCmd: 'install --force --json --no-package-lock'

  - template: pipeline/build.yml@devopsTemplates
    parameters:
      applicationName: ${{variables.applicationFullName}}
      custRegAuth: $(custRegAuth)
      artifactName: "${{variables.applicationShortName}}-dev-$(Build.BuildId)-release"
      environmentName: dev
      environmentId: d01
      pm2ProcessFileName: process.json
      nodeVersionSpec: '14.18.1'
      npmInstCmd: 'install --force --json --no-package-lock'
      npmPruneFixCmd: 'install --production --json --force --no-package-lock'

- stage: Deployment_${{variables.environmentName}}
  displayName: "Deployment [${{variables.environmentName}}]"
  dependsOn: 
  - buildApp
  condition: in(dependencies.buildApp.result, 'Succeeded', 'Skipped')
  jobs:
  - ${{ if parameters.InfrDeploy }}:
    - template: pipeline/infrastructure.yml@devopsTemplates
      parameters:
        serviceConnection: $(devServiceConnection)
        environmentName: dev
        environmentId: d01
        subscriptionId: $(devSubscriptionId)
        applicationShortName: ${{variables.applicationShortName}}
        applicationFullName: ${{variables.applicationFullName}}
        releaseArtifactName: ${{variables.applicationShortName}}-dev-$(Build.BuildId)-release
        certificateName: non-prod-gateway
        AppDeploy: ${{parameters.AppDeploy}}

  - ${{ if parameters.AppDeploy }}:
    - template: pipeline/deploy.yml@devopsTemplates
      parameters: 
        serviceConnection: $(devServiceConnection)
        environmentName: dev
        environmentId: d01
        subscriptionId: $(devSubscriptionId)
        applicationFullName: ${{variables.applicationFullName}}
        applicationShortName: ${{variables.applicationShortName}}
        releaseArtifactName: ${{variables.applicationShortName}}-dev-$(Build.BuildId)-release
        InfrDeploy: ${{parameters.InfrDeploy}}
  