jobs:
- job: filesCheck
  pool:
    vmImage: windows-latest

  steps:
  - task: PowerShell@2
    displayName: Folders/Files changes check 
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/DevOps/scripts/changesChecks.ps1'
      pwsh: true